### ISSUE TITLE
[v3] typescript definition is missing

### ISSUE THREAD

**Issue by sijad** [sergeyshpadyrev/react-native-easy-router#37]

**Comment by sergeyshpadyrev** [comment]
Yes, it's known issue. I'm not very familiar with typescript but I gonna try to create types for it

**Comment by christianchown** [comment]
Hi Sergey

I've just started playing with v3; I have a set of types that I can use to open a PR with. It might be worth following this approach though: 

https://github.com/testing-library/react-testing-library/pull/437
https://blog.johnnyreilly.com/2019/08/symbiotic-definitely-typed.html
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

(*tl;dr* add a dev dependency in package.json to `@types/react-native-easy-router` and let the community maintain the types at DefinitelyTyped)

**Comment by sergeyshpadyrev** [comment]
@christianchown I'm going to return to work on v3 after a long gap. Most important goal now is to add typescript support. I don't like DefinitelyTyped solution very much because react-native-easy-router is not popular enough to have a community that can support types. Anyway it'll be done by me or you so it's better to do it in repo.

**Comment by sergeyshpadyrev** [comment]
So it's done and released in v3.1.0
